services:
  slazero-web:
    build: .
    container_name: slazero-website
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    labels:
      - "com.slazero.description=The world's most honest hosting service"
      - "com.slazero.uptime=0.001%"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
